### ISSUE TITLE
UnhandledRejection when calling the plugin

### ISSUE THREAD

**Issue by oblitum** [iamcco/coc-actions#2]
```
[coc.nvim] error: UnhandledRejection: request error nvim_set_option - E545: Missing colon
Error: request error nvim_set_option - E545: Missing colon
    at /home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
    at NvimTransport.parseMessage (/home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:57:17)
    at DecodeStream.<anonymous> (/home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:27:18)
    at DecodeStream.emit (events.js:321:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/francisco/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
    at DecodeBuffer.flush (/home/francisco/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)
```

**Comment by oblitum** [comment]
I get this error message on NeoVim 0.4.3 when executing the suggested mapping over some text on rust code (using coc-rust-analyzer).

**Comment by oblitum** [comment]
Despite that, the plugin does what is requested, but this errors shows any time it's called.
