### ISSUE TITLE
Pressing <CR> doesnt select the current option

### ISSUE THREAD

**Issue by eloytoro** [iamcco/coc-actions#22]
**Describe the bug**
Pressing <CR> doesnt select the current option

**To Reproduce**
1. Open the actions list anywhere
2. Press <CR>
3. Instead of selecting the action being hovered it moves the cursor to the next action
4. The only way to exit the action list is by executing `:q` because pressing `<Esc>` or `<C-c>` wont work either

**Desktop (please complete the following information):**
 - OS: macos

Log:

```
[coc.nvim]: UnhandledRejection: request error nvim_win_close - Invalid window id: 1018
Error
    at Window.request (/Users/eloy.toro/.config/nvim/plug/coc.nvim/build/index.js:15467:21)
    at Window.close (/Users/eloy.toro/.config/nvim/plug/coc.nvim/build/index.js:15635:21)
    at t.Actions.<anonymous> (/Users/eloy.toro/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:25497)
    at Generator.next (<anonymous>)
    at /Users/eloy.toro/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:23883
    at new Promise (<anonymous>)
    at i (/Users/eloy.toro/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:23628)
    at t.Actions.closeMenu (/Users/eloy.toro/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:25427)
    at callback (/Users/eloy.toro/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:28152)
    at /Users/eloy.toro/.config/nvim/plug/coc.nvim/build/index.js:23668:60
    at Plugin.cocAction (/Users/eloy.toro/.config/nvim/plug/coc.nvim/build/index.js:24038:41)
    at NeovimClient.<anonymous> (/Users/eloy.toro/.config/nvim/plug/coc.nvim/build/index.js:11597:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by iamcco** [comment]
what's your coc-actions version?

**Comment by eloytoro** [comment]
Closing this as im no longer using the plugin
