### ISSUE TITLE
UnhandledRejection on 'CocCommand actions.open'

### ISSUE THREAD

**Issue by tinybeachthor** [iamcco/coc-actions#6]
```
## versions

vim version: NVIM v0.3.8
node version: v10.19.0
coc.nvim version: 0.0.74-bc017b02e6
term: xterm-256color
platform: linux

## Messages
[coc.nvim] error: UnhandledRejection: request error nvim_create_buf - Invalid method: nvim_create_buf
Error: request error nvim_create_buf - Invalid method: nvim_create_buf
    at transport.request (/nix/store/k0xba1y893ryvgd16na65531rxb8v713-vimplugin-coc-nvim-0.0.74/share/vim-plugins/coc-nvim/build/index.js:5899:32)
    at NvimTransport.parseMessage (/nix/store/k0xba1y893ryvgd16na65531rxb8v713-vimplugin-coc-nvim-0.0.74/share/vim-plugins/coc-nvim/build/index.js:2491:17)
    at DecodeStream.NvimTransport.decodeStream.on (/nix/store/k0xba1y893ryvgd16na65531rxb8v713-vimplugin-coc-nvim-0.0.74/share/vim-plugins/coc-nvim/build/index.js:2461:18)
    at DecodeStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:151:32)
    at DecodeBuffer.DecodeStream.decoder.push (/nix/store/k0xba1y893ryvgd16na65531rxb8v713-vimplugin-coc-nvim-0.0.74/share/vim-plugins/coc-nvim/build/index.js:5423:12)
    at DecodeBuffer.flush (/nix/store/k0xba1y893ryvgd16na65531rxb8v713-vimplugin-coc-nvim-0.0.74/share/vim-plugins/coc-nvim/build/index.js:4401:12)
```

**Comment by iamcco** [comment]
Neovim version 0.3.8 do not support float window.

**Comment by tinybeachthor** [comment]
Alright, this could perhaps be mentioned in the readme.
